#!/usr/bin/env bash
# using if and elif and else
count=1
while (( count<=10 )); do

      if (( count == 4 )); then
      	 echo "bad luck"

      elif (( count == 8 )); then
      	   echo "good luck"
      else
	echo "Best School"
      fi

	(( count++ ))
done
