#!/usr/bin/env bash
# some complex task. listening to kill and user interupt signals and printing a meessage endlessly
echo $$ > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
